version: "1.0"
info:
  model: int-scaffold
packages:
- name: Usawco_githubProject
  gitServerName: github
  gitUrl: https://github.com/usawco/Usawco_githubProject
  gitUsername: usawco
  gitBranch: main
